# PX_APPLICATION_NAME = "PainterEngine"
PX_APPLICATION_SURFACE_SIZE = 680

# 内存池的大小，单位为MB
PX_APPLICATION_MEMORYPOOL_UI_SIZE = 8
PX_APPLICATION_MEMORYPOOL_RESOURCES_SIZE = 64
PX_APPLICATION_MEMORYPOOL_GAME_SIZE = 16
PX_APPLICATION_MEMORYPOOL_SPACE_SIZE = 8

frame_rate = 50     # 帧率