# PX_APPLICATION_NAME = "PainterEngine"
PX_APPLICATION_SURFACE_SIZE = 680

# 四个内存池的大小
PX_APPLICATION_MEMORYPOOL_UI_SIZE = 8
PX_APPLICATION_MEMORYPOOL_RESOURCES_SIZE = 64
PX_APPLICATION_MEMORYPOOL_GAME_SIZE = 8
PX_APPLICATION_MEMORYPOOL_SPACE_SIZE = 8