name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write
  deployments: write
  pages: write

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: CMake Build
      run: .\build_win.bat
    - uses: actions/upload-artifact@v3
      with:
        path: build/win/Release/PainterEngine.exe
  build_android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - run: sudo apt-get install ninja-build
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    - name: Build APK
      run: |
        python preprocess.py
        cd as_proj
        ./gradlew --no-daemon assembleDebug
    - uses: actions/upload-artifact@v3
      with:
        path: as_proj/app/build/outputs/apk/debug/app-debug.apk
  build_web:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Setup emsdk
      uses: mymindstorm/setup-emsdk@v12
      with:
        version: 3.1.38
        actions-cache-folder: 'emsdk-cache'
    - name: Compile
      run: bash build_web.sh
    - uses: crazy-max/ghaction-github-pages@v3
      with:
        target_branch: gh-pages
        build_dir: build/web
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: github.repository == 'blueloveTH/pype'
    - uses: actions/upload-artifact@v3
      with:
        path: build
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: CMake Build
      run: |
        sudo apt install libglu1-mesa-dev freeglut3-dev mesa-common-dev
        bash build_linux.sh
    - uses: actions/upload-artifact@v3
      with:
        path: build/linux/PainterEngine
    - uses: actions/upload-artifact@v3
      with:
        path: game